# @package _global_
# 汎用特徴量処理パイプライン設定

pipeline:

  steps:
    # データ品質検証・修復
    - name: "data_validator"
      module: "src.mlops.features.preprocessing"
      class: "DataQualityValidator"
      params:
        fix_dtypes: true
        drop_high_missing: 0.5  # 50%以上欠損列を削除
        drop_zero_variance: true
      columns: "all"

    # データ型最適化（モデル種別対応）
    - name: "dtype_optimizer"
      module: "src.mlops.features.preprocessing"
      class: "DtypeOptimizer"
      params:
        model_name: "${model.name}"  # config参照
        force_dtype: null  # null=自動, "float32"/"float64"で強制指定
      columns: "all"


    # 任意カラムドロップ
    - name: "custom_drop"
      module: "src.mlops.features.selection"
      class: "CustomColumnDropper"
      params:
        columns_to_drop: ["feature_5", "feature_10", "feature_15"]  # テスト用：異なるカラムを削除
      columns: "all"

    # 予測に寄与しなさそうなカラム自動削除
    - name: "auto_drop"
      module: "src.mlops.features.selection"
      class: "LowContributionDropper"
      params:
        variance_threshold: 0.005  # より緩い基準
        correlation_threshold: 0.98  # より厳しい基準
        missing_threshold: 0.3  # より厳しい基準
        constant_threshold: 0.98  # より厳しい基準
      columns: "all"

    # 統計的特徴量選択
    - name: "smart_selection"
      module: "src.mlops.features.selection"
      class: "SmartFeatureSelector"
      params:
        k: 10
        score_func: null  # 自動判定
      columns: "all"

    # スケーリング
    - name: "scaler"
      module: "sklearn.preprocessing"
      class: "StandardScaler"
      params: {}
      columns: "all"

    # サンプリング（不均衡データ対策）
    - name: "sampler"
      module: "imblearn.over_sampling"
      class: "RandomOverSampler"  # SMOTEからRandomOverSamplerに変更
      params:
        sampling_strategy: "auto"
        random_state: ${globals.random_state}
      enabled: true  # true でサンプリング有効化
      columns: "all"