# @package _global_
# ランダムフォレスト回帰モデル設定
model:
  name: "random_forest_regressor"
  module: "sklearn.ensemble"
  class: "RandomForestRegressor"
  default_params:
    n_estimators: 100
    # random_stateはrun.pyで動的に設定される
  optuna_space:
    n_estimators: ["int", 50, 200]
    max_depth: ["int", 3, 20]
    min_samples_split: ["int", 2, 20]
    min_samples_leaf: ["int", 1, 10]