# @package _global_
model:
  name: "gradient_boosting"

models:
  gradient_boosting:
    module: "sklearn.ensemble"
    class: "GradientBoostingClassifier"
    default_params:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 3
    optuna_space:
      n_estimators: ["int", 50, 200]
      learning_rate: ["float", 0.01, 0.3]
      max_depth: ["int", 3, 10]